name: Swift

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: |
        xcodebuild clean test -project Swidoodle.xcodeproj -scheme Swidoodle -destination "platform=iOS Simulator,name=iPhone 11 Pro" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        bash <(curl -s https://codecov.io/bash)
      working-directory: Swidoodle/
